{
  "formatVersion": "1.1",
  "component": {
    "group": "org.panyukovnn",
    "module": "reactive-jdbc-adapter",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "reactive-jdbc-adapter-1.0.0.jar",
          "url": "reactive-jdbc-adapter-1.0.0.jar",
          "size": 4526,
          "sha512": "b8fe2737b81d873fdff9a3e694183af09823fd8aead265c57a950f9359e4753861d54330096deeeaee97ec040e9427729715324e61bf449a6ea09c9bb3a7b4d6",
          "sha256": "0c5ce08c57841d55421ab52546607cc5fdb577d7936ac90680aba0ec140684d9",
          "sha1": "ac8941b03341971b3d7d65572055361d903cfab6",
          "md5": "5f0925a1eebc06bddaf9c24e0f754212"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-webflux",
          "version": {
            "requires": "5.3.22"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-jpa",
          "version": {
            "requires": "2.7.2"
          }
        }
      ],
      "files": [
        {
          "name": "reactive-jdbc-adapter-1.0.0.jar",
          "url": "reactive-jdbc-adapter-1.0.0.jar",
          "size": 4526,
          "sha512": "b8fe2737b81d873fdff9a3e694183af09823fd8aead265c57a950f9359e4753861d54330096deeeaee97ec040e9427729715324e61bf449a6ea09c9bb3a7b4d6",
          "sha256": "0c5ce08c57841d55421ab52546607cc5fdb577d7936ac90680aba0ec140684d9",
          "sha1": "ac8941b03341971b3d7d65572055361d903cfab6",
          "md5": "5f0925a1eebc06bddaf9c24e0f754212"
        }
      ]
    }
  ]
}
